name: Compilation_Test
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo files
        uses: actions/checkout@v4.2.2
      - name: Compile files
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: Presentazione
          root_file: Presentazione.tex
      - name: Upload compiled file
        uses: actions/upload-artifact@v4
        with: 
          name: Presentazione
          path: Presentazione/Presentazione.pdf
